"""
GridAttackSim Model Generation Helper

This script reads a CSV file with a defined format to automatically generate
a basic GridLAB-D model file (.glm). This helps in rapidly creating new
simulation scenarios from structured data.

Expected CSV Header and Example Rows:
object_type,name,from_node,to_node,voltage,length,configuration,phases
node,node1,,,7200,,,ABCN
overhead_line,line1,node1,node2,,2000,lc300,ABCN
transformer,trans1,node2,node3,,,,tc400,ABCN
"""

import csv
import sys
import os

def create_model(input_csv_path, output_glm_path):
    """
    Reads a CSV file and generates a .glm file.
    """
    try:
        with open(input_csv_path, mode='r', newline='') as infile, \
             open(output_glm_path, mode='w') as outfile:

            reader = csv.DictReader(infile)

            outfile.write("// Generated by create_model_from_csv.py\n")
            outfile.write(f"// Source: {os.path.basename(input_csv_path)}\n\n")

            for row in reader:
                obj_type = row.get('object_type', '').strip()
                name = row.get('name', '').strip()

                if not obj_type or not name:
                    continue

                outfile.write(f"object {obj_type} {{\n")
                outfile.write(f"\tname {name};\n")

                # Add properties based on object type
                if obj_type == 'node' and row.get('voltage'):
                    outfile.write(f"\tnominal_voltage {row['voltage']};\n")

                if obj_type in ['overhead_line', 'transformer', 'triplex_line'] and row.get('from_node'):
                    outfile.write(f"\tfrom {row['from_node']};\n")

                if obj_type in ['overhead_line', 'transformer', 'triplex_line'] and row.get('to_node'):
                    outfile.write(f"\tto {row['to_node']};\n")

                if obj_type in ['overhead_line', 'triplex_line'] and row.get('length'):
                    outfile.write(f"\tlength {row['length']};\n")

                if obj_type in ['overhead_line', 'transformer', 'triplex_line'] and row.get('configuration'):
                    outfile.write(f"\tconfiguration {row['configuration']};\n")

                if row.get('phases'):
                    outfile.write(f"\tphases \"{row['phases']}\";\n")

                outfile.write("}\n\n")

        return True, f"Successfully generated {output_glm_path}"

    except FileNotFoundError:
        return False, f"Error: Input file not found at {input_csv_path}"
    except Exception as e:
        return False, f"An unexpected error occurred: {e}"

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python create_model_from_csv.py <input_csv_file> <output_glm_file>")
        sys.exit(1)

    input_csv = sys.argv[1]
    output_glm = sys.argv[2]

    if not os.path.exists(input_csv):
        print(f"Error: Input file not found at {input_csv}")
        sys.exit(1)

    success, message = create_model(input_csv, output_glm)
    print(message)
    if not success:
        sys.exit(1)
